//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.17929。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback uploadDiaryByIdOperationCompleted;
    
    private System.Threading.SendOrPostCallback getNewestDiaryOperationCompleted;
    
    private System.Threading.SendOrPostCallback getDiaryByIdOperationCompleted;
    
    private System.Threading.SendOrPostCallback getDiaryListOperationCompleted;
    
    private System.Threading.SendOrPostCallback logoutOperationCompleted;
    
    private System.Threading.SendOrPostCallback throwsExceptionOperationCompleted;
    
    private System.Threading.SendOrPostCallback sessionedHelloWorldOperationCompleted;
    
    private System.Threading.SendOrPostCallback userRegisterOperationCompleted;
    
    private System.Threading.SendOrPostCallback return1OperationCompleted;
    
    private System.Threading.SendOrPostCallback authenticateOperationCompleted;
    
    private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
    
    /// <remarks/>
    public Service1() {
        this.Url = "http://localhost:1405/Service1.asmx";
    }
    
    /// <remarks/>
    public event uploadDiaryByIdCompletedEventHandler uploadDiaryByIdCompleted;
    
    /// <remarks/>
    public event getNewestDiaryCompletedEventHandler getNewestDiaryCompleted;
    
    /// <remarks/>
    public event getDiaryByIdCompletedEventHandler getDiaryByIdCompleted;
    
    /// <remarks/>
    public event getDiaryListCompletedEventHandler getDiaryListCompleted;
    
    /// <remarks/>
    public event logoutCompletedEventHandler logoutCompleted;
    
    /// <remarks/>
    public event throwsExceptionCompletedEventHandler throwsExceptionCompleted;
    
    /// <remarks/>
    public event sessionedHelloWorldCompletedEventHandler sessionedHelloWorldCompleted;
    
    /// <remarks/>
    public event userRegisterCompletedEventHandler userRegisterCompleted;
    
    /// <remarks/>
    public event return1CompletedEventHandler return1Completed;
    
    /// <remarks/>
    public event authenticateCompletedEventHandler authenticateCompleted;
    
    /// <remarks/>
    public event HelloWorldCompletedEventHandler HelloWorldCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/uploadDiaryById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int uploadDiaryById(int id, Diary d) {
        object[] results = this.Invoke("uploadDiaryById", new object[] {
                    id,
                    d});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginuploadDiaryById(int id, Diary d, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("uploadDiaryById", new object[] {
                    id,
                    d}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EnduploadDiaryById(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void uploadDiaryByIdAsync(int id, Diary d) {
        this.uploadDiaryByIdAsync(id, d, null);
    }
    
    /// <remarks/>
    public void uploadDiaryByIdAsync(int id, Diary d, object userState) {
        if ((this.uploadDiaryByIdOperationCompleted == null)) {
            this.uploadDiaryByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadDiaryByIdOperationCompleted);
        }
        this.InvokeAsync("uploadDiaryById", new object[] {
                    id,
                    d}, this.uploadDiaryByIdOperationCompleted, userState);
    }
    
    private void OnuploadDiaryByIdOperationCompleted(object arg) {
        if ((this.uploadDiaryByIdCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.uploadDiaryByIdCompleted(this, new uploadDiaryByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getNewestDiary", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Diary getNewestDiary() {
        object[] results = this.Invoke("getNewestDiary", new object[0]);
        return ((Diary)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetNewestDiary(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getNewestDiary", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public Diary EndgetNewestDiary(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Diary)(results[0]));
    }
    
    /// <remarks/>
    public void getNewestDiaryAsync() {
        this.getNewestDiaryAsync(null);
    }
    
    /// <remarks/>
    public void getNewestDiaryAsync(object userState) {
        if ((this.getNewestDiaryOperationCompleted == null)) {
            this.getNewestDiaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNewestDiaryOperationCompleted);
        }
        this.InvokeAsync("getNewestDiary", new object[0], this.getNewestDiaryOperationCompleted, userState);
    }
    
    private void OngetNewestDiaryOperationCompleted(object arg) {
        if ((this.getNewestDiaryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getNewestDiaryCompleted(this, new getNewestDiaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDiaryById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Diary getDiaryById(int id) {
        object[] results = this.Invoke("getDiaryById", new object[] {
                    id});
        return ((Diary)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetDiaryById(int id, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getDiaryById", new object[] {
                    id}, callback, asyncState);
    }
    
    /// <remarks/>
    public Diary EndgetDiaryById(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Diary)(results[0]));
    }
    
    /// <remarks/>
    public void getDiaryByIdAsync(int id) {
        this.getDiaryByIdAsync(id, null);
    }
    
    /// <remarks/>
    public void getDiaryByIdAsync(int id, object userState) {
        if ((this.getDiaryByIdOperationCompleted == null)) {
            this.getDiaryByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDiaryByIdOperationCompleted);
        }
        this.InvokeAsync("getDiaryById", new object[] {
                    id}, this.getDiaryByIdOperationCompleted, userState);
    }
    
    private void OngetDiaryByIdOperationCompleted(object arg) {
        if ((this.getDiaryByIdCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getDiaryByIdCompleted(this, new getDiaryByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDiaryList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int[] getDiaryList() {
        object[] results = this.Invoke("getDiaryList", new object[0]);
        return ((int[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetDiaryList(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getDiaryList", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public int[] EndgetDiaryList(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int[])(results[0]));
    }
    
    /// <remarks/>
    public void getDiaryListAsync() {
        this.getDiaryListAsync(null);
    }
    
    /// <remarks/>
    public void getDiaryListAsync(object userState) {
        if ((this.getDiaryListOperationCompleted == null)) {
            this.getDiaryListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDiaryListOperationCompleted);
        }
        this.InvokeAsync("getDiaryList", new object[0], this.getDiaryListOperationCompleted, userState);
    }
    
    private void OngetDiaryListOperationCompleted(object arg) {
        if ((this.getDiaryListCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getDiaryListCompleted(this, new getDiaryListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/logout", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void logout() {
        this.Invoke("logout", new object[0]);
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginlogout(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("logout", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public void Endlogout(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void logoutAsync() {
        this.logoutAsync(null);
    }
    
    /// <remarks/>
    public void logoutAsync(object userState) {
        if ((this.logoutOperationCompleted == null)) {
            this.logoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogoutOperationCompleted);
        }
        this.InvokeAsync("logout", new object[0], this.logoutOperationCompleted, userState);
    }
    
    private void OnlogoutOperationCompleted(object arg) {
        if ((this.logoutCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.logoutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/throwsException", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void throwsException() {
        this.Invoke("throwsException", new object[0]);
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginthrowsException(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("throwsException", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public void EndthrowsException(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void throwsExceptionAsync() {
        this.throwsExceptionAsync(null);
    }
    
    /// <remarks/>
    public void throwsExceptionAsync(object userState) {
        if ((this.throwsExceptionOperationCompleted == null)) {
            this.throwsExceptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnthrowsExceptionOperationCompleted);
        }
        this.InvokeAsync("throwsException", new object[0], this.throwsExceptionOperationCompleted, userState);
    }
    
    private void OnthrowsExceptionOperationCompleted(object arg) {
        if ((this.throwsExceptionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.throwsExceptionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sessionedHelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string sessionedHelloWorld() {
        object[] results = this.Invoke("sessionedHelloWorld", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsessionedHelloWorld(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sessionedHelloWorld", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndsessionedHelloWorld(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void sessionedHelloWorldAsync() {
        this.sessionedHelloWorldAsync(null);
    }
    
    /// <remarks/>
    public void sessionedHelloWorldAsync(object userState) {
        if ((this.sessionedHelloWorldOperationCompleted == null)) {
            this.sessionedHelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsessionedHelloWorldOperationCompleted);
        }
        this.InvokeAsync("sessionedHelloWorld", new object[0], this.sessionedHelloWorldOperationCompleted, userState);
    }
    
    private void OnsessionedHelloWorldOperationCompleted(object arg) {
        if ((this.sessionedHelloWorldCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sessionedHelloWorldCompleted(this, new sessionedHelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/userRegister", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool userRegister(string username, string password) {
        object[] results = this.Invoke("userRegister", new object[] {
                    username,
                    password});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginuserRegister(string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("userRegister", new object[] {
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EnduserRegister(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void userRegisterAsync(string username, string password) {
        this.userRegisterAsync(username, password, null);
    }
    
    /// <remarks/>
    public void userRegisterAsync(string username, string password, object userState) {
        if ((this.userRegisterOperationCompleted == null)) {
            this.userRegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuserRegisterOperationCompleted);
        }
        this.InvokeAsync("userRegister", new object[] {
                    username,
                    password}, this.userRegisterOperationCompleted, userState);
    }
    
    private void OnuserRegisterOperationCompleted(object arg) {
        if ((this.userRegisterCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.userRegisterCompleted(this, new userRegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/return1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string[] return1() {
        object[] results = this.Invoke("return1", new object[0]);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginreturn1(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("return1", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string[] Endreturn1(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public void return1Async() {
        this.return1Async(null);
    }
    
    /// <remarks/>
    public void return1Async(object userState) {
        if ((this.return1OperationCompleted == null)) {
            this.return1OperationCompleted = new System.Threading.SendOrPostCallback(this.Onreturn1OperationCompleted);
        }
        this.InvokeAsync("return1", new object[0], this.return1OperationCompleted, userState);
    }
    
    private void Onreturn1OperationCompleted(object arg) {
        if ((this.return1Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.return1Completed(this, new return1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/authenticate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string authenticate(string username, string password) {
        object[] results = this.Invoke("authenticate", new object[] {
                    username,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginauthenticate(string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("authenticate", new object[] {
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endauthenticate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void authenticateAsync(string username, string password) {
        this.authenticateAsync(username, password, null);
    }
    
    /// <remarks/>
    public void authenticateAsync(string username, string password, object userState) {
        if ((this.authenticateOperationCompleted == null)) {
            this.authenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthenticateOperationCompleted);
        }
        this.InvokeAsync("authenticate", new object[] {
                    username,
                    password}, this.authenticateOperationCompleted, userState);
    }
    
    private void OnauthenticateOperationCompleted(object arg) {
        if ((this.authenticateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.authenticateCompleted(this, new authenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string HelloWorld() {
        object[] results = this.Invoke("HelloWorld", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndHelloWorld(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void HelloWorldAsync() {
        this.HelloWorldAsync(null);
    }
    
    /// <remarks/>
    public void HelloWorldAsync(object userState) {
        if ((this.HelloWorldOperationCompleted == null)) {
            this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
        }
        this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
    }
    
    private void OnHelloWorldOperationCompleted(object arg) {
        if ((this.HelloWorldCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Diary {
    
    private string contentField;
    
    private System.DateTime modifiedField;
    
    private System.DateTime createdField;
    
    private string titleField;
    
    private Management managementField;
    
    /// <remarks/>
    public string content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime modified {
        get {
            return this.modifiedField;
        }
        set {
            this.modifiedField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime created {
        get {
            return this.createdField;
        }
        set {
            this.createdField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public Management management {
        get {
            return this.managementField;
        }
        set {
            this.managementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Management {
    
    private ManagementItem[] itemsField;
    
    /// <remarks/>
    public ManagementItem[] items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class ManagementItem {
    
    private System.DateTime addTimeField;
    
    private int itemTypeField;
    
    /// <remarks/>
    public System.DateTime addTime {
        get {
            return this.addTimeField;
        }
        set {
            this.addTimeField = value;
        }
    }
    
    /// <remarks/>
    public int itemType {
        get {
            return this.itemTypeField;
        }
        set {
            this.itemTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void uploadDiaryByIdCompletedEventHandler(object sender, uploadDiaryByIdCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class uploadDiaryByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal uploadDiaryByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void getNewestDiaryCompletedEventHandler(object sender, getNewestDiaryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getNewestDiaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getNewestDiaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Diary Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Diary)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void getDiaryByIdCompletedEventHandler(object sender, getDiaryByIdCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getDiaryByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getDiaryByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Diary Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Diary)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void getDiaryListCompletedEventHandler(object sender, getDiaryListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getDiaryListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getDiaryListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void logoutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void throwsExceptionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void sessionedHelloWorldCompletedEventHandler(object sender, sessionedHelloWorldCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sessionedHelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sessionedHelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void userRegisterCompletedEventHandler(object sender, userRegisterCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class userRegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal userRegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void return1CompletedEventHandler(object sender, return1CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class return1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal return1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void authenticateCompletedEventHandler(object sender, authenticateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class authenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal authenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
